export interface NRItem {
  id: string;
  texto: string;
  conforme: boolean;
  observacao?: string;
  foto?: string;
  critico?: boolean;
}

export interface NRTemplate {
  norma: string;
  label: string;
  descricao: string;
  cor: string;
  icone: string;
  categoria: string;
  itens: NRItem[];
}

export const NR_TEMPLATES: Record<string, NRTemplate> = {
  'NR-5': {
    norma: 'NR-5',
    label: 'NR-5 — CIPA',
    descricao: 'Comissão Interna de Prevenção de Acidentes',
    cor: '#0A84FF',
    icone: '🛡️',
    categoria: 'Gestão',
    itens: [
      { id: '1', texto: 'CIPA constituída e registrada no MTE', conforme: false, critico: true },
      { id: '2', texto: 'Membros eleitos e designados conforme dimensionamento', conforme: false },
      { id: '3', texto: 'Reuniões mensais realizadas e documentadas', conforme: false },
      { id: '4', texto: 'Mapa de riscos elaborado e afixado', conforme: false, critico: true },
      { id: '5', texto: 'Presidente e vice-presidente eleitos', conforme: false },
      { id: '6', texto: 'Ata das reuniões arquivadas', conforme: false },
      { id: '7', texto: 'Treinamento dos membros da CIPA realizado', conforme: false },
    ],
  },
  'NR-6': {
    norma: 'NR-6',
    label: 'NR-6 — EPI',
    descricao: 'Equipamentos de Proteção Individual',
    cor: '#30D158',
    icone: '🦺',
    categoria: 'Proteção',
    itens: [
      { id: '1', texto: 'EPIs adequados disponíveis para todos os trabalhadores', conforme: false, critico: true },
      { id: '2', texto: 'EPIs dentro do prazo de validade', conforme: false, critico: true },
      { id: '3', texto: 'CA (Certificado de Aprovação) válido para todos os EPIs', conforme: false, critico: true },
      { id: '4', texto: 'Trabalhadores treinados para uso correto dos EPIs', conforme: false },
      { id: '5', texto: 'Registro de entrega de EPIs assinado pelos trabalhadores', conforme: false },
      { id: '6', texto: 'EPIs armazenados adequadamente e higienizados', conforme: false },
      { id: '7', texto: 'EPIs danificados substituídos imediatamente', conforme: false, critico: true },
      { id: '8', texto: 'Ficha de EPI preenchida e atualizada', conforme: false },
    ],
  },
  'NR-7': {
    norma: 'NR-7',
    label: 'NR-7 — PCMSO',
    descricao: 'Programa de Controle Médico de Saúde Ocupacional',
    cor: '#FF6B6B',
    icone: '🏥',
    categoria: 'Saúde',
    itens: [
      { id: '1', texto: 'PCMSO elaborado por médico do trabalho', conforme: false, critico: true },
      { id: '2', texto: 'Exames admissionais realizados', conforme: false, critico: true },
      { id: '3', texto: 'Exames periódicos em dia para todos os funcionários', conforme: false, critico: true },
      { id: '4', texto: 'ASO (Atestado de Saúde Ocupacional) arquivados', conforme: false },
      { id: '5', texto: 'Exames demissionais realizados', conforme: false },
      { id: '6', texto: 'Programa de vacinação implementado quando necessário', conforme: false },
      { id: '7', texto: 'Relatório anual do PCMSO elaborado', conforme: false },
    ],
  },
  'NR-9': {
    norma: 'NR-9',
    label: 'NR-9 — PPRA',
    descricao: 'Programa de Prevenção de Riscos Ambientais',
    cor: '#5E5CE6',
    icone: '🌿',
    categoria: 'Ambiental',
    itens: [
      { id: '1', texto: 'PPRA elaborado e implementado', conforme: false, critico: true },
      { id: '2', texto: 'Agentes físicos, químicos e biológicos identificados', conforme: false, critico: true },
      { id: '3', texto: 'Medições de agentes ambientais realizadas', conforme: false },
      { id: '4', texto: 'Medidas de controle coletivas implementadas', conforme: false },
      { id: '5', texto: 'Trabalhadores informados sobre os riscos', conforme: false },
      { id: '6', texto: 'Documento Base do PPRA assinado pela empresa', conforme: false },
      { id: '7', texto: 'PPRA revisado anualmente', conforme: false },
    ],
  },
  'NR-10': {
    norma: 'NR-10',
    label: 'NR-10 — Eletricidade',
    descricao: 'Segurança em Instalações e Serviços com Eletricidade',
    cor: '#FFD60A',
    icone: '⚡',
    categoria: 'Elétrica',
    itens: [
      { id: '1', texto: 'Trabalhadores com treinamento NR-10 atualizado', conforme: false, critico: true },
      { id: '2', texto: 'Quadros elétricos identificados, sinalizados e trancados', conforme: false, critico: true },
      { id: '3', texto: 'Distâncias de segurança respeitadas', conforme: false, critico: true },
      { id: '4', texto: 'Ferramentas isoladas para trabalhos elétricos com CA', conforme: false },
      { id: '5', texto: 'EPIs elétricos disponíveis (luvas, capacetes classe B)', conforme: false, critico: true },
      { id: '6', texto: 'Procedimentos LOTO (bloqueio e etiquetagem) implementados', conforme: false, critico: true },
      { id: '7', texto: 'Instalações elétricas em conformidade com ABNT NBR 5410', conforme: false },
      { id: '8', texto: 'Aterramento das instalações verificado e documentado', conforme: false },
      { id: '9', texto: 'Prontuário das instalações elétricas atualizado', conforme: false },
    ],
  },
  'NR-11': {
    norma: 'NR-11',
    label: 'NR-11 — Transporte',
    descricao: 'Transporte, Movimentação, Armazenagem e Manuseio de Materiais',
    cor: '#FF9F0A',
    icone: '🏗️',
    categoria: 'Operações',
    itens: [
      { id: '1', texto: 'Operadores de equipamentos com habilitação/treinamento', conforme: false, critico: true },
      { id: '2', texto: 'Manutenção preventiva dos equipamentos em dia', conforme: false, critico: true },
      { id: '3', texto: 'Capacidade de carga respeitada em todos os equipamentos', conforme: false, critico: true },
      { id: '4', texto: 'Sinalização de circulação de veículos e pedestres', conforme: false },
      { id: '5', texto: 'Armazenagem de materiais de forma segura e organizada', conforme: false },
      { id: '6', texto: 'Dispositivos de segurança dos equipamentos funcionando', conforme: false, critico: true },
    ],
  },
  'NR-12': {
    norma: 'NR-12',
    label: 'NR-12 — Máquinas',
    descricao: 'Segurança no Trabalho em Máquinas e Equipamentos',
    cor: '#FF3B30',
    icone: '⚙️',
    categoria: 'Máquinas',
    itens: [
      { id: '1', texto: 'Proteções fixas e móveis instaladas em todas as máquinas', conforme: false, critico: true },
      { id: '2', texto: 'Dispositivos de parada de emergência funcionando', conforme: false, critico: true },
      { id: '3', texto: 'Distâncias de segurança respeitadas', conforme: false, critico: true },
      { id: '4', texto: 'Sinalização de segurança nas máquinas e equipamentos', conforme: false },
      { id: '5', texto: 'Manual de operação disponível em português', conforme: false },
      { id: '6', texto: 'Trabalhadores treinados para operação segura', conforme: false },
      { id: '7', texto: 'Manutenção preventiva em dia com registro', conforme: false },
      { id: '8', texto: 'Laudo de conformidade NR-12 atualizado', conforme: false, critico: true },
    ],
  },
  'NR-17': {
    norma: 'NR-17',
    label: 'NR-17 — Ergonomia',
    descricao: 'Ergonomia',
    cor: '#32ADE6',
    icone: '🧘',
    categoria: 'Saúde',
    itens: [
      { id: '1', texto: 'Análise ergonômica do trabalho realizada', conforme: false, critico: true },
      { id: '2', texto: 'Postos de trabalho adaptados às características dos trabalhadores', conforme: false },
      { id: '3', texto: 'Mobiliário ajustável e adequado', conforme: false },
      { id: '4', texto: 'Equipamentos de trabalho adequados à tarefa', conforme: false },
      { id: '5', texto: 'Condições ambientais (iluminação, ruído, temperatura) adequadas', conforme: false },
      { id: '6', texto: 'Pausas e intervalos respeitados conforme legislação', conforme: false },
      { id: '7', texto: 'Trabalhadores treinados sobre posturas corretas', conforme: false },
    ],
  },
  'NR-18': {
    norma: 'NR-18',
    label: 'NR-18 — Construção Civil',
    descricao: 'Condições e Meio Ambiente na Construção',
    cor: '#FF6B35',
    icone: '🏚️',
    categoria: 'Construção',
    itens: [
      { id: '1', texto: 'PCMAT elaborado e implementado', conforme: false, critico: true },
      { id: '2', texto: 'Instalações sanitárias: banheiros e vestiários adequados', conforme: false },
      { id: '3', texto: 'Refeitório e local para refeição disponíveis', conforme: false },
      { id: '4', texto: 'Andaimes e escadas em boas condições e fixados', conforme: false, critico: true },
      { id: '5', texto: 'Redes de proteção contra queda de materiais instaladas', conforme: false, critico: true },
      { id: '6', texto: 'Sinalização perimetral do canteiro de obras', conforme: false },
      { id: '7', texto: 'Almoxarifado organizado e seguro', conforme: false },
      { id: '8', texto: 'Trabalhadores com NR-18 em dia', conforme: false },
      { id: '9', texto: 'Descarte correto de resíduos da construção civil', conforme: false },
      { id: '10', texto: 'Área de vivência completa e em boas condições', conforme: false },
    ],
  },
  'NR-20': {
    norma: 'NR-20',
    label: 'NR-20 — Inflamáveis',
    descricao: 'Segurança e Saúde com Inflamáveis e Combustíveis',
    cor: '#FF3B30',
    icone: '🔥',
    categoria: 'Risco',
    itens: [
      { id: '1', texto: 'Inflamáveis armazenados em local adequado e sinalizado', conforme: false, critico: true },
      { id: '2', texto: 'Fichas de informação de segurança (FISPQ) disponíveis', conforme: false, critico: true },
      { id: '3', texto: 'Equipamentos antiexplosão utilizados onde necessário', conforme: false, critico: true },
      { id: '4', texto: 'Trabalhadores treinados para manipulação de inflamáveis', conforme: false, critico: true },
      { id: '5', texto: 'Sistema de aterramento dos recipientes verificado', conforme: false },
      { id: '6', texto: 'Licenças e alvarás dos tanques em dia', conforme: false },
    ],
  },
  'NR-21': {
    norma: 'NR-21',
    label: 'NR-21 — Trabalho a Céu Aberto',
    descricao: 'Trabalho a Céu Aberto',
    cor: '#30D158',
    icone: '☀️',
    categoria: 'Ambiental',
    itens: [
      { id: '1', texto: 'Proteção contra insolação excessiva e calor', conforme: false, critico: true },
      { id: '2', texto: 'Abrigos para proteção contra chuva e frio disponíveis', conforme: false },
      { id: '3', texto: 'Água potável fresca disponível no local de trabalho', conforme: false, critico: true },
      { id: '4', texto: 'Protetor solar fornecido e aplicado pelos trabalhadores', conforme: false },
      { id: '5', texto: 'Intervalos de descanso em local fresco respeitados', conforme: false },
      { id: '6', texto: 'Atividades interrompidas em condições climáticas de risco', conforme: false },
    ],
  },
  'NR-23': {
    norma: 'NR-23',
    label: 'NR-23 — Incêndio',
    descricao: 'Proteção Contra Incêndios',
    cor: '#FF3B30',
    icone: '🧯',
    categoria: 'Emergência',
    itens: [
      { id: '1', texto: 'Extintores disponíveis, sinalizados e dentro do prazo', conforme: false, critico: true },
      { id: '2', texto: 'Sinalização de saídas de emergência visível e iluminada', conforme: false, critico: true },
      { id: '3', texto: 'Rotas de fuga completamente desobstruídas', conforme: false, critico: true },
      { id: '4', texto: 'Hidrantes e mangueiras em boas condições de uso', conforme: false },
      { id: '5', texto: 'Treinamento de combate a incêndio realizado', conforme: false },
      { id: '6', texto: 'Brigada de incêndio formada e treinada', conforme: false, critico: true },
      { id: '7', texto: 'Planta de evacuação afixada em locais visíveis', conforme: false },
      { id: '8', texto: 'Materiais inflamáveis armazenados separados de ignição', conforme: false },
    ],
  },
  'NR-26': {
    norma: 'NR-26',
    label: 'NR-26 — Sinalização',
    descricao: 'Sinalização de Segurança',
    cor: '#FFD60A',
    icone: '🚧',
    categoria: 'Sinalização',
    itens: [
      { id: '1', texto: 'Sinalização de segurança instalada em todos os locais de risco', conforme: false, critico: true },
      { id: '2', texto: 'Cores padronizadas conforme NR-26 (vermelho, amarelo, verde, azul)', conforme: false },
      { id: '3', texto: 'Sinalização de tubulações e equipamentos', conforme: false },
      { id: '4', texto: 'Sinalizações em bom estado de conservação e limpeza', conforme: false },
      { id: '5', texto: 'Sinalização de áreas de circulação e armazenamento', conforme: false },
      { id: '6', texto: 'Proibições e obrigatoriedades claramente sinalizadas', conforme: false },
    ],
  },
  'NR-33': {
    norma: 'NR-33',
    label: 'NR-33 — Espaços Confinados',
    descricao: 'Segurança e Saúde em Espaços Confinados',
    cor: '#5E5CE6',
    icone: '🕳️',
    categoria: 'Risco',
    itens: [
      { id: '1', texto: 'Espaços confinados identificados, cadastrados e sinalizados', conforme: false, critico: true },
      { id: '2', texto: 'Permissão de Entrada e Trabalho (PET) emitida', conforme: false, critico: true },
      { id: '3', texto: 'Vigias treinados NR-33 e designados no local', conforme: false, critico: true },
      { id: '4', texto: 'Equipamentos de monitoramento de gases disponíveis e calibrados', conforme: false, critico: true },
      { id: '5', texto: 'Equipamentos de resgate disponíveis no local', conforme: false, critico: true },
      { id: '6', texto: 'Ventilação mecânica adequada do espaço', conforme: false, critico: true },
      { id: '7', texto: 'Comunicação contínua entre entrador e vigia', conforme: false },
      { id: '8', texto: 'Trabalhadores com treinamento NR-33 atualizado', conforme: false, critico: true },
    ],
  },
  'NR-35': {
    norma: 'NR-35',
    label: 'NR-35 — Trabalho em Altura',
    descricao: 'Trabalho em Altura (acima de 2 metros)',
    cor: '#0A84FF',
    icone: '🧗',
    categoria: 'Altura',
    itens: [
      { id: '1', texto: 'Trabalhadores com treinamento NR-35 atualizado', conforme: false, critico: true },
      { id: '2', texto: 'Cinturão tipo paraquedista com CA válido', conforme: false, critico: true },
      { id: '3', texto: 'Trava-quedas e talabarte duplo em boas condições', conforme: false, critico: true },
      { id: '4', texto: 'Pontos de ancoragem adequados, identificados e testados', conforme: false, critico: true },
      { id: '5', texto: 'Plano de Resgate elaborado e comunicado a todos', conforme: false, critico: true },
      { id: '6', texto: 'Análise de Risco (AR) realizada antes da atividade', conforme: false, critico: true },
      { id: '7', texto: 'Sinalização e isolamento da área abaixo do trabalho', conforme: false },
      { id: '8', texto: 'Condições climáticas avaliadas (sem chuva, raios ou ventos)', conforme: false, critico: true },
      { id: '9', texto: 'Capacete com jugular em uso', conforme: false },
      { id: '10', texto: 'Ferramentas com trava/cordão anti-queda', conforme: false },
    ],
  },
};

export const NR_LIST = Object.values(NR_TEMPLATES);

export const NR_CATEGORIAS = [
  'Todas',
  'Proteção',
  'Saúde',
  'Gestão',
  'Construção',
  'Elétrica',
  'Máquinas',
  'Risco',
  'Emergência',
  'Altura',
  'Operações',
  'Ambiental',
  'Sinalização',
];
